module.exports = {
  choice: require('./choice'),
  clr: require('./clr'),
  img: require('./img'),
  input: require('./input'),
  ln: require('./ln'),
  loadState: require('./loadState'),
  nextTick: require('./nextTick'),
  runFlow: require('./runFlow'),
  saveState: require('./saveState'),
  sdl: require('./sdl'),
  sec: require('./sec'),
  speech: require('./speech'),
  sspk: require('./sspk'),
  storyAppend: require('./storyAppend'),
  str: require('./str'),
  w: require('./w'),
};
